import { Toaster } from 'react-hot-toast';
import Providers from './Providers';
import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />
        <div className="flex justify-end mx-4">
          <Link
            className="inline-block rounded bg-indigo-400 px-8 py-3 text-sm font-medium text-white transition hover:scale-110 hover:shadow-xl focus:outline-none focus:ring active:bg-indigo-300"
            target="_blank"
            href={'https://www.linkedin.com/in/venkatagurrala/'}
          >
            LinkedIn
          </Link>
        </div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
